# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = '[{"name":"multiple-ui-changes-from-3.1.2","base":"v3.1.2"}]'

oarepo_major_version = "12"

package_oarepo_version = "oarepo-4.1.0"

configuration = '{"name": "invenio-administration", "oarepo": 13, "features": [{"name": "multiple-ui-changes-from-3.1.2", "base": "v3.1.2"}], "package": "invenio-administration", "invenio_version": "4.1.0", "version": "4.1.0"}'
